---
version: "3.8"
services:
  postgres:
    image: "postgres:13-alpine"
    environment:
    - "POSTGRES_USER=p9"
    - "POSTGRES_PASSWORD=prodigy9"
    - "POSTGRES_DB=p9"
    ports:
    - "0.0.0.0:5432:5432"

